//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asopalav.GetDailyGoldRateServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://freewebservicesx.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://freewebservicesx.com/", ConfigurationName="GetDailyGoldRateServiceReference.GetGoldPriceSoap")]
    public interface GetGoldPriceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://freewebservicesx.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://freewebservicesx.com/GetCurrentGoldPrice", ReplyAction="*")]
        Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponse GetCurrentGoldPrice(Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://freewebservicesx.com/GetCurrentGoldPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponse> GetCurrentGoldPriceAsync(Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentGoldPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentGoldPrice", Namespace="http://freewebservicesx.com/", Order=0)]
        public Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequestBody Body;
        
        public GetCurrentGoldPriceRequest() {
        }
        
        public GetCurrentGoldPriceRequest(Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://freewebservicesx.com/")]
    public partial class GetCurrentGoldPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public GetCurrentGoldPriceRequestBody() {
        }
        
        public GetCurrentGoldPriceRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentGoldPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentGoldPriceResponse", Namespace="http://freewebservicesx.com/", Order=0)]
        public Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponseBody Body;
        
        public GetCurrentGoldPriceResponse() {
        }
        
        public GetCurrentGoldPriceResponse(Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://freewebservicesx.com/")]
    public partial class GetCurrentGoldPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Asopalav.GetDailyGoldRateServiceReference.ArrayOfString GetCurrentGoldPriceResult;
        
        public GetCurrentGoldPriceResponseBody() {
        }
        
        public GetCurrentGoldPriceResponseBody(Asopalav.GetDailyGoldRateServiceReference.ArrayOfString GetCurrentGoldPriceResult) {
            this.GetCurrentGoldPriceResult = GetCurrentGoldPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetGoldPriceSoapChannel : Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGoldPriceSoapClient : System.ServiceModel.ClientBase<Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap>, Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap {
        
        public GetGoldPriceSoapClient() {
        }
        
        public GetGoldPriceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetGoldPriceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetGoldPriceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetGoldPriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponse Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap.GetCurrentGoldPrice(Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest request) {
            return base.Channel.GetCurrentGoldPrice(request);
        }
        
        public Asopalav.GetDailyGoldRateServiceReference.ArrayOfString GetCurrentGoldPrice(string UserName, string Password) {
            Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest inValue = new Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest();
            inValue.Body = new Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponse retVal = ((Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap)(this)).GetCurrentGoldPrice(inValue);
            return retVal.Body.GetCurrentGoldPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponse> Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap.GetCurrentGoldPriceAsync(Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest request) {
            return base.Channel.GetCurrentGoldPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceResponse> GetCurrentGoldPriceAsync(string UserName, string Password) {
            Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest inValue = new Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequest();
            inValue.Body = new Asopalav.GetDailyGoldRateServiceReference.GetCurrentGoldPriceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((Asopalav.GetDailyGoldRateServiceReference.GetGoldPriceSoap)(this)).GetCurrentGoldPriceAsync(inValue);
        }
    }
}
