//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceVariant
    {
        public long PriceVariantId { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductPriceUnit { get; set; }
        public Nullable<decimal> PreviousPrice { get; set; }
        public Nullable<int> PriceMasterId { get; set; }
        public Nullable<decimal> PriceChangePercentage { get; set; }
        public string ActionPeformed { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual PriceMaster PriceMaster { get; set; }
    }
}
