//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceMaster()
        {
            this.PriceVariants = new HashSet<PriceVariant>();
        }
    
        public int PriceId { get; set; }
        public decimal PriceValue { get; set; }
        public string PriceMeasure { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> MetalId { get; set; }
        public Nullable<int> GemId { get; set; }
        public Nullable<System.DateTime> EffectiveFor { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual GemVariant GemVariant { get; set; }
        public virtual MetalVariant MetalVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceVariant> PriceVariants { get; set; }
    }
}
