//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public long ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public decimal WeightInGms { get; set; }
        public string Height_width_inch { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsOffer { get; set; }
        public decimal OfferPrice { get; set; }
        public string SmallImage { get; set; }
        public string BigImage { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
    
        public virtual ProductTypeMaster ProductTypeMaster { get; set; }
    }
}
