//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressDetail
    {
        public long Address_id { get; set; }
        public long Login_Id { get; set; }
        public string Bill_Name { get; set; }
        public string Bill_Email { get; set; }
        public string Bill_Mobile { get; set; }
        public string Bill_Addr_Line1 { get; set; }
        public string Bill_Addr_Line2 { get; set; }
        public string Bill_City { get; set; }
        public string Bill_State { get; set; }
        public string Bill_Country { get; set; }
        public int Bill_Pin { get; set; }
        public string Ship_Name { get; set; }
        public string Ship_Email { get; set; }
        public string Ship_Mobile { get; set; }
        public string Ship_Addr_Line1 { get; set; }
        public string Ship_Addr_Line2 { get; set; }
        public string Ship_City { get; set; }
        public string Ship_State { get; set; }
        public string Ship_Country { get; set; }
        public int Ship_Pin { get; set; }
    
        public virtual UserProfileMaster UserProfileMaster { get; set; }
    }
}
