//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asopalav.GetDailySilverRateServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://freewebservicesx.com/", ConfigurationName="GetDailySilverRateServiceReference.GetSilverPriceSoap")]
    public interface GetSilverPriceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://freewebservicesx.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://freewebservicesx.com/GetCurrentSilverPrice", ReplyAction="*")]
        Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponse GetCurrentSilverPrice(Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://freewebservicesx.com/GetCurrentSilverPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponse> GetCurrentSilverPriceAsync(Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentSilverPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentSilverPrice", Namespace="http://freewebservicesx.com/", Order=0)]
        public Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequestBody Body;
        
        public GetCurrentSilverPriceRequest() {
        }
        
        public GetCurrentSilverPriceRequest(Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://freewebservicesx.com/")]
    public partial class GetCurrentSilverPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public GetCurrentSilverPriceRequestBody() {
        }
        
        public GetCurrentSilverPriceRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentSilverPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentSilverPriceResponse", Namespace="http://freewebservicesx.com/", Order=0)]
        public Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponseBody Body;
        
        public GetCurrentSilverPriceResponse() {
        }
        
        public GetCurrentSilverPriceResponse(Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://freewebservicesx.com/")]
    public partial class GetCurrentSilverPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentSilverPriceResult;
        
        public GetCurrentSilverPriceResponseBody() {
        }
        
        public GetCurrentSilverPriceResponseBody(string GetCurrentSilverPriceResult) {
            this.GetCurrentSilverPriceResult = GetCurrentSilverPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetSilverPriceSoapChannel : Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSilverPriceSoapClient : System.ServiceModel.ClientBase<Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap>, Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap {
        
        public GetSilverPriceSoapClient() {
        }
        
        public GetSilverPriceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetSilverPriceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSilverPriceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSilverPriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponse Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap.GetCurrentSilverPrice(Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest request) {
            return base.Channel.GetCurrentSilverPrice(request);
        }
        
        public string GetCurrentSilverPrice(string UserName, string Password) {
            Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest inValue = new Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest();
            inValue.Body = new Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponse retVal = ((Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap)(this)).GetCurrentSilverPrice(inValue);
            return retVal.Body.GetCurrentSilverPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponse> Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap.GetCurrentSilverPriceAsync(Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest request) {
            return base.Channel.GetCurrentSilverPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceResponse> GetCurrentSilverPriceAsync(string UserName, string Password) {
            Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest inValue = new Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequest();
            inValue.Body = new Asopalav.GetDailySilverRateServiceReference.GetCurrentSilverPriceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((Asopalav.GetDailySilverRateServiceReference.GetSilverPriceSoap)(this)).GetCurrentSilverPriceAsync(inValue);
        }
    }
}
